# Generated by Django 5.0.4 on 2024-04-21 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drive", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={("file", "user")},
        ),
    ]
